name: Security Scan

on:
  schedule:
    - cron: '0 8 * * 1'  # Runs at 8:00 AM every Monday
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  security:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Run npm audit
        run: npm audit
        continue-on-error: true
